# CodeRabbit Configuration
# Frontend-heavy Next.js repository

language: en

reviews:
  auto_review: true
  review_status: true
  high_level_summary: true
  request_changes_workflow: true

  path_filters:
    - "**/*.ts"
    - "**/*.tsx"
    - "**/*.js"
    - "**/*.jsx"
    - "**/*.css"
    - "**/*.json"
    - "**/*.md"
    - "**/*.yaml"
    - "**/*.yml"
    # Exclude assets
    - "!**/*.ico"
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.jpeg"
    - "!**/*.gif"
    - "!**/*.svg"
    - "!**/*.webp"

files:
  ignore:
    - "**/*.ico"
    - "**/*.png"
    - "**/*.jpg"
    - "**/*.jpeg"
    - "**/*.gif"
    - "**/*.svg"
    - "**/*.webp"
    - "**/favicon.ico"
    - "**/public/**/*"
